### ISSUE TITLE
小程序的NFC接口能做什么呢？

### ISSUE THREAD

**Issue by JoyHuYY1412** [lambertlei/wxMiniProgressStudy#1]
请问使用微信小程序的NFC接口，能够读取一些NFC标签里面的信息吗？如果不能，现在能怎么实现呢？谢谢！

**Comment by fpleihub** [comment]
小程序目前开放的是HCE模式的NFC功能，非Reader模式的功能，所有小程序NFC目前暂时不能作为读取器，只能作为卡（被读）对象。小程序目前无法实现Reader，看后期企鹅会不会开放吧

**Comment by JoyHuYY1412** [comment]
谢谢回复！但是我想，如果是想读取RFID标签，小程序的蓝牙接口应该也可以做到吧？不知道您有没有经验呢？

**Comment by fpleihub** [comment]
蓝牙和NFC不同的模块，之间不能做到不同模块的访问吧，Tag是针对NFC来的

**Comment by JoyHuYY1412** [comment]
thx
